### PR TITLE
Handle all contact import exceptions

### PR DESCRIPTION
**Pull request by darrick**
See if I'm able to resolve this merge on your PR via the Web interface.  Internet says I should be able to do that.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@darrick my version has changed since you wrote that code against it - you probably need to do a `git pull --rebase eileen contact_out`

**Comment by darrick** [comment]
@eileenmcnaughton I'll see if I can also do that via the web interface.  Fixing the conflicts was certainly easy.

**Comment by darrick** [comment]
Not ready I'm trying our gh pr checkout 15

**Comment by darrick** [comment]
Well maybe just applying the diff will work for you.  I'm not sure how to easily squash it.

**Comment by eileenmcnaughton** [comment]
@darrick maybe I should rebase this whole branch over https://github.com/civicrm/civicrm-core/pull/23669 then - that is going to be merged in the next few hours so it might give you a cleaner test base

**Comment by eileenmcnaughton** [comment]
actually I should be able to copy that in

**Comment by darrick** [comment]
@eileenmcnaughton I'd like to just take a step back for now.  I can always try to just do a PR later in the week.  I'll get back to my code and see what else crops up.  It's getting late here on the weekend.  Through this whole time working with you I've really learned a lot and up my game as far as my development environment.  But rebasing and merging is still a bit beyond me at times.

**Comment by eileenmcnaughton** [comment]
@darrick I have pulled in your changes to mine & also rebased over the import_queue PR which is to be merged soon. It was a bit messy so I'm about to re-run tests - but I think my branch currently reflects our best combined wisdom

**Pull request closed without merging**
